### ISSUE TITLE
Event Locatin Page

### ISSUE THREAD

**Issue by hbutau** [PyZim/pyzim.github.io#13]
A page about the event venue. It can have  a Google Map!

**Comment by JohananOppongAmoateng** [comment]
@hbutau  Please is there a ui to use for building this page

**Comment by ronnzw** [comment]
> @hbutau Please is there a ui to use for building this page

@JohananOppongAmoateng we don't have a specific UI in mind but you can use [this](https://za.pycon.org/venue/venue-details/) for inspiration. The venue is at the following coordinates.( -17.819752943250446, 31.056869802407405)

**Comment by JohananOppongAmoateng** [comment]
@hbutau this issue needs to be closed
