### ISSUE TITLE
Mission, Vision, and Objectives Page

### ISSUE THREAD

**Issue by hbutau** [PyZim/pyzim.github.io#14]

**Comment by JohananOppongAmoateng** [comment]
ui?

**Comment by JohananOppongAmoateng** [comment]
I would like to work on this issue can i get assigned to it

**Comment by JohananOppongAmoateng** [comment]
@hbutau can the mission objective and anyother thing I need to put on the page. Also a UI would not be bad. Thank you

**Comment by ronnzw** [comment]
## Mission 
To have a diverse and sustainable community of python developers, educators,  enthusiast, data scientists, sponsors in and around Zimbabwe. We want to create a vibrant community that is engaging and willing to take Python programming language back to their communities.

## Vision
To be the go to community for all Python people in Zimbabwe.

## Objective
- Integrate back the Zimbabwean Python community to the rest of the world
- To find new community leaders
- To bridge the tribal and regional gap in our community
- Encourage the local corporates to be involved in the Python community.

@hbutau feel free to add any other things that l might have missed. @JohananOppongAmoateng this is a good starting point for you.

**Comment by JohananOppongAmoateng** [comment]
@hbutau this issue needs to be closed
