### ISSUE TITLE
Add opening remarks

### ISSUE THREAD

**Issue by ronnzw** [PyZim/PyZim.github.io#25]
We need to add opening remarks on Day 2 schedule. The conference chair should give the remarks.

**Comment by cliffordgama** [comment]
I suppose this should be added before the keynote speaker. But how do you propose to reshuffle the slots to make this fit, and what time would be allocated to the opening remarks?

**Comment by ronnzw** [comment]
> I suppose this should be added before the keynote speaker. But how do you propose to reshuffle the slots to make this fit, and what time would be allocated to the opening remarks?

Shorten the registration time. It will be only 15 mins.
