### ISSUE TITLE
LinkedIn link is broken.

### ISSUE THREAD

**Issue by cliffordgama** [PyZim/PyZim.github.io#26]
It doesn't seem to be implemented, anyway.

**Comment by hbutau** [comment]
check here: pyconzim.co.zw

**Comment by cliffordgama** [comment]
While we're on this, is it intentional that the team members' social media links all point to Pycon Zimbabwe's own social media pages? I was going to open another issue for that.

**Comment by hbutau** [comment]
Its not intentional. You can go ahead. Can I assign this to you @cliff688

**Comment by hbutau** [comment]
And for that let's have LinkedIn and X only.

**Comment by cliffordgama** [comment]
Sure. I can work on that.

**Comment by cliffordgama** [comment]
Why is it that there are two sites: https://zw.pycon.org/ (outdated but that's the one search engines pick up) and https://pyconzim.co.zw/ (which I only know about because you pointed it out to me). I'd say that's another issue, and a more pressing one.

**Comment by hbutau** [comment]
Wea re

> Why is it that there are two sites: https://zw.pycon.org/ (outdated but that's the one search engines pick up) and https://pyconzim.co.zw/ (which I only know about because you pointed it out to me). I'd say that's another issue, and a more pressing one.

we are not in control of the other domain. The owners are working on it.

**Comment by cliffordgama** [comment]
Why are files not updating? I see that there were 6 commits today but I can't find them, and GitHub says the repo was last updated 2 mo ago?

**Comment by hbutau** [comment]
> Why are files not updating? I see that there were 6 commits today but I can't find them, and GitHub says the repo was last updated 2 mo ago?
 @cliff688 fixed by #33
