### ISSUE TITLE
Remove Ditiro's workshop

### ISSUE THREAD

**Issue by ronnzw** [PyZim/PyZim.github.io#28]
Remove Ditiro from the speakers list as the speaker has cancelled last minute. Workshops are there on the 31 October.
<img width="688" alt="Screenshot 2024-10-22 at 01 54 10" src="https://github.com/user-attachments/assets/6e79c5dd-24ba-4231-b0d9-ed173ac50093">

**Comment by hbutau** [comment]
We need a replacement.
