### ISSUE TITLE
Sponsors demarcation

### ISSUE THREAD

**Issue by ronnzw** [PyZim/PyZim.github.io#30]
We need to clearly demarcate the sponsor levels as specified below.

- PSF Platinum sponsor 
- DSF community
- DEFNA community
- Black Python Devs Bronze - (diversity sponsor)
- AWS community sponsor

This means the PSF should have a visibly bigger size logo than the rest of them. Reduce size for community sponsors, you can put them in one line. Then Black Python Devs in #29 can be put on it's own but again visible smaller than PSF but bigger than community sponsors.

Also add a thank you tag, something like: "We would like to that our sponsors. "
<img width="1408" alt="Screenshot 2024-10-22 at 23 07 47" src="https://github.com/user-attachments/assets/eb002d3b-b2b2-4f96-8807-18192f48cd5b">

**Comment by cliffordgama** [comment]
So, Platinum is highest, followed by diversity then community?

**Comment by ronnzw** [comment]
> So, Platinum is highest, followed by diversity then community?

correct

**Comment by hbutau** [comment]
fixed by #
