### ISSUE TITLE
Add social media links for the team

### ISSUE THREAD

**Issue by cliffordgama** [PyZim/PyZim.github.io#37]
@hbutau I have started working on this following up on [our discussion here](https://github.com/PyZim/PyZim.github.io/issues/26#issuecomment-2425678771). Decided to create a new issue here to separate concerns.

Problem: I noticed that team members have only their first names. It is difficult to find their social media links with just those. Any way you can provide the full names of the users or their social links.

**Comment by cliff688** [comment]
[PR](https://github.com/PyZim/PyZim.github.io/pull/40)
