### ISSUE TITLE
Pelican documentation

### ISSUE THREAD

**Issue by ronnzw** [PyZim/pyzim.github.io#6]
## Introduction
Currently we have a `readme.rst` which content about how to use pelican. We need to update the content so that it's more beginner friendly and add instruction for contributors

## Tasks
- creation of virtual environments
- forking, branch naming format, cloning and other basic contribution guide
- basic description of what pelican is
- instruction of what to include in the Pull Request

**Comment by hbutau** [comment]
@ronnzw  I am on it in #7

**Comment by ronnzw** [comment]
@hbutau thanks
