### ISSUE TITLE
Color change of links

### ISSUE THREAD

**Issue by ronnzw** [PyZim/pyzim.github.io#8]
Change the yellow color it is difficult to see for those that are visually impaired. Change it to the standard blue color.
<img width="846" alt="Screenshot 2024-06-12 at 12 56 38" src="https://github.com/PyZim/PyZim.github.io/assets/17087071/fd533ed8-afbe-4172-aeab-21c3c8b1759b">

**Comment by hbutau** [comment]
Fixed in #15
